name: Auto Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      USER_NAME:
        description: 'User Name in Github Account'
        required: true
        default: ''
      USER_EMAIL:
        description: 'E-mail in Github Account'
        required: true
        default: ''
      FIRMWARE_URL:
        description: 'Stock ROM Link'
        required: true
        default: ''

jobs:
  dump:
    name: Auto Firmware Dumper
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    permissions: write-all
    steps:

    - name: Check Out
      uses: actions/checkout@v4

    - name: Setup
      run: |
        sudo bash setup.sh
        echo "${GH_TOKEN}" >> .githubtoken

    - name: Dump Firmware
      run: |
        git config --global user.name "${{ inputs.USER_NAME }}"
        git config --global user.email "${{ inputs.USER_EMAIL }}"
        sudo bash dumpyara.sh ${{ inputs.FIRMWARE_URL }}
